- docs/advanced/tls_porting.md
A new interface has been introduced in the hal and it is the new
preferred way to enable mbed TLS using the TRNG on a new platform.
This PR updates the porting guide to reflect this change.
> Update TLS porting guide

- docs/advanced/debugging.md
- docs/collab/collab_intro.md
- docs/collab/mult_auth.md
- docs/collab/publishing_code.md
- docs/collab/pull_requests.md
- docs/collab/versions.md
- docs/dev_tools/online_comp.md
- docs/getting_started/blinky_cli.md
Add captions to all images in latest version of Handbook
Note: Captions format weird in preview, but I merged one as a test, and it looks fine on the page
> Add captions to Handbook images

- docs/getting_started/examples.md
Added:
- Nanostack Border Router
- Filesystem
- Bootloader
- Bootloader blinky
Removed:
- BLE URI beacon (deprecated)
@iriark01 @sg-
> Update list of examples for mbed OS 5.4

- docs/debugging/vscode.md
These issues are fixed in mbed OS.
@AnotherButler @iriark01
> Update vscode to remove gdb configuration, and the note on Windows paths

- docs/dev_tools/online_comp.md
The difference between the first two compiler options isn't what
programs in your workspace are built but whether an incremental or
clean build is performed.
Addresses issue #132.
> Correct online compiler compile menu options

- docs/advanced/toolchain_profiles.md
They were incorrectly omitted.
> Add ld flags to toolchain profile document

- docs/advanced/DAP.md
- mkdocs.yml
Remove CMSIS-DAP which is confused with DAPLink, otherwise we need give more description for CMSIS-DAP and the difference between CMSIS-DAP and DAPLink.
> Remove CMSIS-DAP which is confused with DAPLink

- docs/advanced/exporters.md
As per title; see the mbed-os [pull request 4115](https://github.com/ARMmbed/mbed-os/pull/4115).
> Added documentation about the Qt Creator export

- docs/dev_tools/third_party.md
Resolves https://github.com/ARMmbed/mbed-os/issues/3890
@AnotherButler
@pan-
> Expand on use of debug profile in the exporters

- docs/debugging/debugging_eclipse_pyocd.md
@AnotherButler @c1728p9 - Review Required
> Added Note for GNU-Make utility requirement

- docs/advanced/bootloader.md
Documentation for https://github.com/ARMmbed/mbed-os/pull/4202
> Add documentation of Unmanaged Bootloader builds

- docs/advanced/config_system.md
Documentation for https://github.com/ARMmbed/mbed-os/pull/4387
> Document noncumulative target overrides

- docs/advanced/cmsis-rtos.md
Document CMSIS-RTOS and RTX usage in mbed OS.
Should be merged after https://github.com/ARMmbed/mbed-os/pull/4294 
@AnotherButler could you please have a look
> Add CMSIS-RTOS documentation

- docs/dev_tools/options.md
Update GNU ARM Embedded link to point to latest update
> Update link in options.md

- docs.json
@iriark01 
This is just tidying up the indentation of the json file and removing the deprecated example_panel option which is no longer used.
> Fix indentaion and remove deprecated example_panel option

- docs/dev_tools/build_profiles.md
This change will be needed when https://github.com/ARMmbed/mbed-os/pull/4097 is merged.
> Build profile docs change related to sleep

- docs/dev_tools/third_party.md
Added IAR version information to the "Exporting to third party Toolchains" page, since the [mbed-cli docs](https://github.com/ARMmbed/mbed-cli#through-mbed_settingspy) explicitly state that IAR versions older or newer than 7.80 will likely be incompatible with the tools.
Relevant mbed developer question: https://developer.mbed.org/questions/78375/use-iar-system-811-recompile-found-error/
> Add IAR version information

- docs/advanced/mbed_targets.md
Documentation for https://github.com/ARMmbed/mbed-os/pull/4215
> Add documentation of the targets linter script

- docs/advanced/runtime_stats.md
Runtime memory stats page was outdated and wasn't correct. This PR improves the docs, cleans up the syntax and make sure the instructions are up to date.
@AnotherButler @c1728p9
> Improve memory stats page

- docs/refs/api/drivers/AnalogIn.md
The description is insufficient. Expanding for fuller explanation. 
Further removing Example 3 as it does nothing to add explanation or deeper understanding to the API. The code is not commented and is confusing. 
I would suggest pruning both the remaining examples (1 and 2) as they are likewise not terribly useful, but i'll leave them to be addressed at a later date.
> expand AnalogIn Description

- docs/refs/api/storage/block_device.md
- docs/refs/api/storage/filesystem.md
- docs/refs/api/storage/storage_intro.md
I cleaned up the Storage API references section:
- Fixed typos
- Formatted the code examples with correct image links and sub-headings
- Added class/library reference links to BlockDevice and FileSystem
- Moved lengthy descriptions to storage_intro.md
> Storage API section cleanup

- docs/refs/api/rtos/rtos_intro.md
the order of paragraphs in the rtos intro did not make sense. Re-organized so they make more sense.
> Re-order rtos intro

- docs/refs/porting/mbed_os_targets.md
Add a porting note on physical LED and Button naming conventions to address [this issue](https://github.com/ARMmbed/mbed-os/issues/4880#issuecomment-323544403).
Open to any additions to this segment.
@AnotherButler
> Add porting note for LED and button naming

- docs/refs/api/platform/sleep.md
- sleep API
- sleep manager (new in mbed OS 5.6)
This depends on https://github.com/ARMmbed/mbed-os/pull/4912 , as this one gets to 5.6, this should be part of 5.6 documentation. I noticed all PR are to the new_engine branch, this also then.
The aim is to describe how sleep API should work, new API for sleep manager API (use `DeepSleepLock` class in applications). 
An example there was inspired based on SPI changes we did, we can either point directly to the file, or keep this, or any other suggestions?
> Add sleep API documentation

- docs/refs/api/drivers/PortOut.md
the example code pointed to PWMOut, not PortOut, updated link accordingly
> update example program

- docs/refs/porting/mbed_targets.md
- docs/tutorials/first_app/blinky_cli.md
- docs/tutorials/optimize/memory/memap.md
> Add ARMC6 where appropriate

- docs/contributing/systick_tickless.md
CC: @AnotherButler @c1728p9 @0xc0170
> Add page about systick and tickless mode

- docs/contributing/sleep_deep_sleep.md
Status: *Work in progress*
It's basically Martin's proposal.
@c1728p9 @0xc0170
> Porting guide: Add Sleep API pg page

- docs/contributing/rtc.md
Initial draft of RTC HAL page for PG
CC: @c1728p9 @0xc0170
> Add RTC HAL page to PG

- docs/reference/api/platform/Callback.md
Update the brief example explanation text for the Sonar example to reference the introduction to callback docs page rather than saying "...uses everything discussed..." which was a hold over from when it was written as one document.
@AnotherButler
> Update Sonar example text

- docs/getting_started/blinky_cli.md
I added some notes about detecting the name of the user's target board name for compilation. Finding the name of the target was not immediately obvious for new users.
> Added additional info related to target platforms

- docs/reference/api/drivers/RawSerial.md
I didn't want to pull over and copy all of the Serial examples as that wouldn't add much. Tried to show examples closer to the use case of RawSerial, let me know if you think it's not sufficient or should be changed to something else.
@sg-
> Add API specification for RawSerial class

- docs/tools/debug/build_script.md
bulid_script.md was in the wrong place, and none of the contents could have gone
here. All of the information contained in this file is either so out of date
that it's no longer relevant, or are contained in other files. Most of this
information was made irrelevant by the introduction of Mbed CLI.
> Remove build_script.md

- docs/reference/api/storage/ChainingBlockDevice.md
@AnotherButler I put in a link to the HeapBlockDevice class reference page for now as a cross reference. Let me know if you'd like different links.
@sg-
> Add Chaining block device api docs

- docs/reference/contributing/tools/mbedls.md
I had to mess with the template provided as partners do not implement Mbed-ls
support, and as such it would really be hard for them to have bugs when
implementing it. The section titles need to be revised as they do not map well
into the way I would describe "making mbed-ls detect a new target".
> Fill out mbed-ls "contributing" guide

- docs/reference/api/platform/CriticalSectionLock.md
Added an example to demonstrate race condition and usage of critical section api. Also updated the description for API.
https://jira.arm.com/browse/IOTMORF-1286
@AnotherButler  @sg- Please review
> Critical Section doc update

- docs/reference/api/connectivity/networksocket/UDPSocket.md
Jira: https://jira.arm.com/browse/IOTMORF-1309
Added the example reference of UDP client
@sg- Please review
> UDP sockect doc update

- docs/reference/api/storage/ChainingBlockDevice.md
SlicingBlockDevice acts as an opposite for this class, add in reference to it.
@sg-
> Add link to SlicingBlockDevice

- docs/reference/api/storage/ProfilingBlockDevice.md
The class reference link will be broken until the above PR is merged and the doxygen docs are regenerated.
@sg-
> Add ProfilingBlockDevice API doc

- docs/reference/contributing/target/exporter.md
- docs/reference/contributing/target/flash.md
- docs/reference/contributing/target/target.md
- docs/tools/mbed_targets.md
Link to this document from all of the places that used to incorrectly link
to the exporters documentation
I also notice someone changed the links from markdown style to HTML
style since I last edited this document. I don't think this is a great
idea, but if you want me to recreate those changes on this branch, I can.
Resolves https://github.com/ARMmbed/mbed-os/issues/4057
> Move `device_has` docs into targets.json docs

- docs/reference/api/platform/platform.md
Update code example to use correct variable. The sample before would store the state of two low pass filter results in one variable.
@kegilbert @geky
> Correct importance of state code sample

- docs/reference/api/platform/Rtc.md
- docs/reference/api/platform/Time.md
Updated RTC and Time API document.
@AnotherButler - Changes are valid for mbed-os 5.6 as well, shall I create one more PR for that?
@sg- Please review
> RTC and time API pages updated

- docs/reference/api/rtos/ConditionVariable.md
Add a description and example for the ConditionVariable class.
> Add documentation for the ConditionVariable class

- docs/reference/contributing/storage/storage.md
Make new PR from old PR I'm closing to avoid merge conflicts.
> Make PR from #324

- docs/reference/api/platform/CriticalSectionLock.md
CriticalSection Class was update and new member functions were added. See https://jira.arm.com/browse/IOTMORF-1773 and https://github.com/ARMmbed/mbed-os/pull/5621 for more info.
> CriticalSection Class Update (MERGE version - mbed-os-5.8)

- docs/reference/api/drivers/Ticker.md
- docs/reference/api/platform/SleepManager.md
Remove information about the 30-minute limitation from the Ticker docs, as the newer API is not limited by this. Add a note to about the higher power consumption of ticker. Add a note to SleepManager indicating that sleep() should not need to be called normally. Also explicitly reference classes which are safe to use in deep sleep mode.
> Update Ticker and SleepManager based on feedback

- docs/tools/toolchains/export_to_third_party.md
Add requested content to satisfy internal ref: IOTMORF-1786.
> Add content to export_to_third_party.md

- docs/reference/api/rtos/MemoryPool.md
Fix the documentation to clarify that its the calloc function which sets the memory to zeroes.
> Fix MemoryPool docs to capture the difference between alloc/calloc

- docs/reference/contributing/guidelines/workflow.md
We would like to show users how a good pull request look like.  I used code highlight for the template, is that fine or better solutions ?
The main points that should be coevred:
- describe your changes (what is being changed and how)
- how it was tested (targets, toolchains, etc)
- pull request type (can be one of, not a mixture!)
The template is being updated here https://github.com/ARMmbed/mbed-os/pull/6078
> PR template addition

- docs/reference/contributing/guidelines/workflow.md
There are lot of changes (I can split some restructuring from this if that would make it easier but the changes are not that significant to the text itself). I can rebase after the review (squash fix typos and similar commits).
Rendered file [here](https://github.com/0xc0170/Handbook/blob/dbb470799ba8ef58823a3c8670fcf50ac778232c/docs/reference/contributing/guidelines/workflow.md)
The new structure is:
- gatekeepers (maintainers + stakeholders)
- contributions
- pull requests categories and states
- additional labels
New additions here:
- introducing feature branches
- stakeholders (feature owners or module owners)
- time boxes for each pull request stage
Please assign for review maintainers (@theotherjimmy @adbridge @cmonr )
@studavekar (there is one reference to CI that is currently …
> Workflow document update

- docs/reference/contributing/guidelines/style.md
Just a minor thing, I tried the suggested astyle command line options and got an error
I changed `--indents-switches` to `--indent-switches` and it worked
> fix typo in astyle command line options

- docs/tools/bootloader.md
- docs/tutorials/bootloader.md
@AnotherButler, where should we link this from?
> Add BL parameter definitions as new document

- docs/reference/contributing/target/sleep.md
Update the Sleep PG to match the HAL template.
@AnotherButler we still need to correct the links to point out to doxy for feature branches when available.
> Use template for sleep PG

- docs/reference/api/connectivity/networksocket/EthInterface.md
> Mbed OS 5.8 brings support for network interface status change callback

- docs/reference/contributing/storage/storage.md
HeapBlockDevice is an inheritor of the BlockDevice class. The related content and block device porting section should reference extending the BlockDevice class, not one of its implementations.
@AnotherButler
> Replace references to heapblock with blockdevice

- check_tools/find_bad_doxy_references.py
Usage:
``` bash
$ python check_tools/find_bad_doxy_references.py docs/reference
```
Example output:
``` bash
$ ./check_tools/find_bad_doxy_references.py docs/reference
docs/reference/contributing/target/rtc.md:36: Bad URL (https):
https://os-doc-builder.test.mbed.com/docs/development/mbed-os-api-doxy/rtc__api_8h_source.html
.
docs/reference/contributing/target/rtc.md:40: Bad URL (-1):
http://os-do-builder.test.mbed.com/docs/development/feature-hal-spec-rtc-doxy/group__hal__rtc.
html
...................................................................................................                                                                                         
Done!
```
cc @AnotherButler, @kegilbert
> Add script to find bad doxygen references

- docs/reference/contributing/target/lp_ticker.md
- docs/reference/contributing/target/rtc.md
- docs/reference/contributing/target/sleep.md
- docs/reference/contributing/target/us_ticker.md
Just a few typos.
I'm assuming that the phrase 'ticker times increments' is meant to be singular 'time' that increments, but they may also mean that ticker 'times' (plural) increment (without the 's'). Either way, one needs to be changed.
> Contr API Ref Typos

- docs/tools/offline/cli-create.md
Add new content about repository caching.
> Add new content to cli-create.md

- docs/reference/contributing/target/usb.md
Fill in the USB contributing page for the HAL USBPhy API.
> Initial draft of the HAL USBPhy API

- docs/reference/api/connectivity/lorawan/lorawanconfig.md
Matches the connectivity style:
https://github.com/ARMmbed/Handbook/blob/new_engine/docs/reference/configuration/Connectivity.md
@AnotherButler
> Change config parameters to proper format

- docs/reference/contributing/target/lp_ticker.md
Rename  LOWPOWERTICKER to LPTICKER HAL macro name to be consistent with USTICKER.
Depends on: https://github.com/ARMmbed/mbed-os/pull/6351
> Rename LOWPOWERTICKER to LPTICKER

- docs/reference/contributing/target/lp_ticker.md
- docs/reference/contributing/target/us_ticker.md
Some of the tests were renamed not to confuse users, update porting guide to reflect this.
Code already merged to mbed-os repo.
> Replace us_lp tests reference with common_ticker

- docs/reference/contributing/guidelines/design_guidelines.md
While looking at documentation it became apparent that we didn't have
a design guideline for the usage of doxygen tags or our internal
policy with regards to deprecation written down publicly.
I dont know how the @ sign will render so feel free to use some fancy markup if needed to beautify this on the website.
> Add deprecated section and notes about doxygen usage

- docs/reference/api/connectivity/bluetooth/Gap.md
- docs/reference/api/connectivity/bluetooth/SecurityManager.md
There were a few things that were unclear in this section:
In the 1st paragraph of the Security Manger section:
The phrase 'process of pairing and optionally bonding' in the 2nd sentence is a little confusing. Are these two parts of one process?, i.e. 'the pairing and optionally bonding process provides this'?  Or, are they two separate processes? - in which case it should say: 'The pairing and optionally bonding processes provide this.' (I took a guess from the context that they are two separate but related processes, and that the latter was meant?)
2nd paragraph of the Security Manager section:
I changed 'process of pairing' to 'pairing process' again (in the 3rd paragraph it is called the 'pairing process' and I thought this might sound better?)
The next sentence (2nd paragraph, 2nd …
> TBD corrections 3

- docs/reference/api/connectivity/networksocket/EthInterface.md
- docs/reference/api/connectivity/networksocket/WifiInterface.md
> Updated ethernet and wifi interface description 

- docs/reference/api/api.md
- docs/reference/api/connectivity/networksocket/EthInterface.md
- docs/reference/api/connectivity/networksocket/MeshInterface.md
- docs/reference/api/connectivity/networksocket/networksocket.md
- docs/reference/technology/connectivity/networking.md
- docs/reference/technology/mesh/thread_intro.md
+ Use descriptive link ID
+ Use relative links, not absolute. Makes it cleaner.
For future, when I link to Socket API, I want to use link id which is `socket-api.html`, easier to remember, and cleaner.
I believe this is now according to `Publishing guide` -> `Text styling - the technical details`
CC: @AnotherButler Please review
> Refactor Socket API links.

- docs/reference/api/api.md
- docs/reference/api/connectivity/networksocket/EthInterface.md
- docs/reference/api/connectivity/networksocket/MeshInterface.md
- docs/reference/api/connectivity/networksocket/networksocket.md
- docs/reference/technology/connectivity/networking.md
- docs/reference/technology/mesh/thread_intro.md
* Fix the render engine bug found in https://github.com/ARMmbed/Handbook/pull/497
@iriark01 @AnotherButler Please merge in, so Socket-API links will be fixed.
> Fix Socket API link by using same ID in the "title" field in docs.json

- docs/reference/contributing/guidelines/workflow.md
Every PR type should be clear to a user.
It is a user responsibility to specify PR type and accept the versioning based on it.
Fixes #429
Proposal to define PR types. I would like to reference this in every pull request so all of us are aware of the responsibility to select the proper type and the release label selection based on that.
Needs more work to be more clear and specify more details, expecting lot of comments 🔥 
@sg- @cmonr @adbridge @theotherjimmy @kjbracey-arm Please review
> workflow: add PR types explanation

- docs/reference/contributing/target/QuadSPI.md
Tests still needs to be written (To be implemented in that section)
@SenRamakri Please review.
> QSPI: add contributing guide

- docs/reference/contributing/target/lp_ticker.md
Add a section with information about low power ticker synchronization and using LOWPOWERTIMER_DELAY_TICKS to address this problem.
> Add synchronization delay section in lp ticker

- docs/reference/contributing/guidelines/style.md
Depends on https://github.com/ARMmbed/mbed-os/pull/6014 (once it lands), we got astyle options and ignore paths.
I added documentation to cover the new option file and ignore paths (a mention that 3rd parties libraries should not be formatted).
Any other suggestions for this update? We are adding this check to travis, shall we mention it there  that automatic checks are done for all changes?
@adbridge @theotherjimmy @cmonr @kjbracey-arm Please review (@AnotherButler can you add them as reviewers)
> AStyle update (use options and ignore file for astyle)

- docs/reference/contributing/target/rtos.md
https://github.com/ARMmbed/mbed-os/pull/6773/files
> Added timer/idle thread conf

- docs/tools/bootloader.md
- docs/tutorials/bootloader.md
This feature is in 5.8.0 onward, and can be merged into the 5.8 documentation
> Specify application header format in manager bl mode

- docs/reference/api/platform/MbedStats.md
- docs/reference/api/platform/MemoryStats.md
Changes as per below mentioned PR's. Should wait for all of them to be merged to master. 
1. https://github.com/ARMmbed/mbed-os/pull/6795. 
2. https://github.com/ARMmbed/mbed-os/pull/6821
3. https://github.com/ARMmbed/mbed-os/pull/6857
Target Release 5.9
> Update Statistics document - Thread/System/CPU API addition

- docs/reference/api/connectivity/networksocket/networksocket.md
* Remove obsolete and outdated examples
* Add diagram from Technology page
* Explain the API a bit
* Extend the non-blocking section
> Update network socket APIs overview page

- docs/reference/contributing/connectivity/ethernet.md
Remove mention about feature branch, these are now in master.
Tell about the README.md in test directory.
@AnotherButler Please review & merge in. We would like to have this before OOB.
> Update Ethernet porting guide.

- docs/reference/api/platform/Rtc.md
- docs/reference/api/platform/Time.md
- docs/reference/api/platform/Wait.md
Aligned to other API docs, API's were listed as static code, instead of linking to doxy.
> Aligned to other API docs

- docs/reference/api/platform/Error.md
Documentation for Standardized Error handling feature in Mbed-OS. This includes descriptions on various aspects of error handling implementation and also contains reference to Doxygen documentation for this feature provided as part of mbed_error.h.
> Mbed OS Standardized Error handling documentation

- docs/reference/configuration/mesh.md
This was removed from the Cloud documentation. Moving it here as Alon proposed.
> Adding a note about the mesh configuration files.

- docs/reference/contributing/target/lp_ticker.md
- docs/reference/contributing/target/rtc.md
- docs/reference/contributing/target/sleep.md
- docs/reference/contributing/target/us_ticker.md
Sleep, tickers (lp and us), RTC APIs are merged to master. This PR removes feature branch vs master distinction.
> Sleep, tickers, RTC APIs are now on master

- docs/reference/api/security/TLS.md
Information on how Mbed TLS is shipped with Mbed OS and details on what's included.
@AnotherButler
> Mbed TLS details for Mbed OS

- docs/reference/api/drivers/Devicekey.md
Fix typos raised in IOTDOCS-502.
> Fix typos in Devicekey.md

- docs/tutorials/bootloader.md
Make the link to mbed-os-example-bootloader more prominent by removing code formatting. Also remove out of date line referencing the example mbed-os-example-bootloader-blinky.
> Update bootloader tutorial

- docs/reference/contributing/guidelines/workflow.md
I would like to address new triage comments in Github issues. To inform users we triage, and leave some comments in the issues + label. Please review
This is addressing questions like this one https://github.com/ARMmbed/mbed-os/issues/7190#issuecomment-396563501
> workflow: add triage comment

- docs/reference/configuration/Platform.md
This updates the platform configurations options with all new items.
This depends on: https://github.com/ARMmbed/mbed-os/pull/7214
> Updating Platform config page with latest configs

- docs/reference/contributing/target/lp_ticker.md
- docs/reference/contributing/target/target.md
- docs/tools/mbed_targets.md
Update the name in the docs to reflect the code.
> Rename LOWPOWERTIMER to LPTICKER

- check_tools/point_to_new_version.py
This script generates a note for each doc page that is out of date, with a link that takes users to the most recent doc page. If it can't find a recent doc page, it will ask the user which url to use. It uses existing notes and remembers answers in an effort to reduce the number questions forwarded to the user.
Originally I attempted to parse docs.json but could not get this to work well enough.
note: Don't merge until first successful run
cc @AnotherButler, @kegilbert
> Add script for updating notes to most recent doc pages

- docs/reference/api/drivers/RawSerial.md
- docs/reference/api/drivers/Serial.md
[Example three in the Serial API doc](https://os.mbed.com/docs/latest/reference/serial.html#example-three) attaches an interrupt to the Serial `pc` object, and inside the callback function `getc()` and `putc()` are used. As of the latest version of Mbed OS, both of these functions use mutex locks which are not allowed in ISR context, and create the following error at runtime:
```
++ MbedOS Error Info ++
Error Status: 0x80010133 Code: 307 Module: 1
Error Message: Mutex: 0x20000F1C, Not allowed in ISR context
Location: 0x1002B29
Error Value: 0x20000F1C
Current Thread: Id: 0x20002850 Entry: 0x10040C9 StackSize: 0x1000 StackMem: 0x20001810 SP: 0x2003FE50 
-- MbedOS Error Info --
```
In order to use `getc()` and `putc()` in ISR context with a serial interrupt, you need to use a …
> Move Serial example 3 to RawSerial

- docs/tools/offline/cli-create.md
This PR adds instructions on how a user can use the MBED_OS_DIR config within Mbed CLI to manage multiple Mbed projects that use the same version of Mbed OS (and therefore the same Mbed OS directory/copy).
> Add instructions on how to compile multiple projects with one copy of Mbed OS

- docs/tools/mbed_targets.md
Please add a note about the --source switch affecting where cli expected custom_targets.json, something like I wrote here, as it's kind of a "gotcha"
> Add note about where CLI looks for custom_targets.json

- docs/tools/offline/cli-setup.md
Based on feedback during a workshop.
TLDR: the download link for the installer needs to be the first and biggest link in the section. We saw that during the workshop users just downloaded the first link they saw, which previously was just the mbed CLI link or the windows serial driver link. With this change we are making the first and foremost link the one for the installer to look similar to the OSX installer link.
> Update windows installer instructions

- docs/reference/api/storage/storage.md
In general, all links seem to be the full paths. Shouldn't they be just the short forms, starting with /docs...?
> FlashIAP driver link fix.

- docs/tutorials/using_apis/events_tutorial.md
Fixed EventQueue API tutorial bugs
- Updated events_ex_1 here: https://os.mbed.com/teams/mbed_example/code/events_ex_1/file/69c11c7877b6/main.cpp/
> Fix EventQueue API tutorial bugs

- docs/reference/technology/connectivity/lora-tech.md
A note is added in the Technology section related to LoRaWAN.
It tries to clarify the difference between LoRaPHY and LoRaRadio.
> Adding note for LoRaPHY & LoRaRadio clarification

- docs/reference/contributing/target/rtos.md
- docs/reference/contributing/target/target.md
- docs/reference/contributing/target/tickless.md
This PR is for update the testing section in the contributing docs.
ref. `IOTHAL-56`
following updates included
* add testing section in the rtos page
* add testing section in the target page
* update the doxgen links in the tickless page
> Update testing section in the contributing docs

- docs/tools/offline/cli-collaborate.md
- docs/tools/testing/testing.md
`mbed export` hasn't placed exported projects in the `projectfiles` directory for quite some time. They are now placed in the root directory.
FYI @theotherjimmy
> Removing mention of the export 'projectfiles' directory

- docs/reference/api/platform/SharedPtr.md
This is the associated documentation PR for https://github.com/ARMmbed/mbed-os/pull/7815.
> Add documentation for shared pointer class

- docs/tools/offline/cli-compile.md
- docs/tools/offline/cli-setup.md
> Document Arm Compiler switching based on arch version

- docs/reference/contributing/target/QuadSPI.md
Align docs with changes introduced in:
https://github.com/ARMmbed/mbed-os/pull/7817
https://github.com/ARMmbed/mbed-os/pull/7783
> Update QSPI porting guide

- docs/reference/api/platform/MemTrace.md
- docs/tutorials/optimize/memory/runtime_mem_trace.md
https://github.com/ARMmbed/mbed-os/pull/7402  Was merged, this is good to go.
> Move mem_tracing from macro setting to using the MbedOS Config Settings

- docs/tutorials/optimize/memory/runtime_stats.md
> Add example link instead hard coded in doc

- docs/reference/api/platform/Span.md
- docs/reference/api/platform/platform.md
This is the associated documentation PR for ARMmbed/mbed-os#7828.
> Add platform/Span documentation.

- docs/reference/api/platform/MbedStats.md
- docs/reference/api/platform/MemTrace.md
- docs/tutorials/optimize/memory/runtime_mem_trace.md
https://github.com/ARMmbed/mbed-os/issues/7343
> Add overhead info for memory trace / stats

- docs/reference/contributing/target/QuadSPI.md
Remove reference to "future API" and separate PR requirements in the contributing doc now that QSPI is mainlined. Also cleaned up the intro slightly. 
@AnotherButler We seem to switch between `QSPI` and `QuadSPI` throughout the doc, should we stick to one or the other?
@maciejbocianski
> Minor QSPI contributing cleanup

- docs/reference/api/drivers/QuadSPI.md
Delete link to example until example is updated and made public.
> Delete example from QuadSPI.md

- docs.json
- docs/introduction/examples.md
- docs/reference/api/security/security.md
- docs/reference/configuration/uVisor.md
- docs/reference/contributing/target/rtos.md
- docs/tools/debug/local_debugging_toolchain.md
- docs/tools/mbed_targets.md
should be merged after #654 
depends on https://github.com/ARMmbed/mbed-os/pull/7592
> Remove uVisor

- docs/tools/offline/cli-test-debug.md
Introductory documentation for unit testing framework.
depends on ARMmbed/mbed-os#7819 and ARMmbed/mbed-cli#734
Superseeds #677
> Document Unit Testing

- docs.json
JSON format was invalid due to missing string termination.
@AnotherButler
> Close string quotes in docs.json

- docs/reference/contributing/connectivity/CellularInterface.md
I've done a few grammar fixes to help the document read better (FYI @AnotherButler).
I've also fixed a greentea link since #659 was merged.
> [5.10 OOB] Cellular porting fixes

- docs/tools/offline/cli-device-management.md
Related to https://github.com/ARMmbed/mbed-cli/issues/746  (INTERNAL MBOTRIAGE-1595) 
In order to temporarily enable OOB and users of the `mbed dm` feature, we should add in this Note. 
This does not solve the overarching issue about a Developer vs Administrator API key allowing to generate a developer credentials file.
> Note about permissions

- docs/tools/testing/testing_intro.md
Move testing overview content and diagram to testing overview page to resolve issue #718
> Move content to testing_intro.md

- docs/tools/offline/cli-device-management.md
Change links to resolve issue #725
> Change links in cli-device-managment.md

- docs/reference/api/security/TLS.md
- docs/reference/contributing/target/hw-accelerated-crypto.md
1. Add guidelines for Applications to call the platform API
2. Add guidelines on how to port an alternative platform context.
> Create guidelines for the mbedtls_platform_context

- docs/tools/fastmodels/fastmodels.md
This PR adds information about using the DS-5 installation to load Mbed OS images to the FVP platforms provided in DS-5. Also information on adding the DS-5 bin folder to the system PATH
> FastModels - Add information about DS-5 and add to PATH

- docs/tutorials/optimize/memory/runtime_mem_trace.md
Overhead is added only in case of memory stats and not memory trace
> Corrected overhead limitation

- docs/reference/contributing/guidelines/workflow.md
+ define what is a component
Questions:
- regarding components: we might want to list all of available or would it be clear from Mbed OS structure?
- I defined "ready for merge" as: does not mean it will be instantly merged, expecting to be checked during gatekeeping but most cases (simple PR) can be merged immediately - how it is
- we are still missing here  the information about our CI @OPpuolitaival I would like your help here to add a section here to add `CI` and provide info about public information that we have on each pull request (separate PR that would address this)
cc @SeppoTakalo @AnttiKauppila @ARMmbed/mbed-os-maintainers
> Add labels to PR stages

- docs/reference/configuration/Platform.md
- docs/reference/configuration/RTOS.md
Update Platform and RTOS configuration sections to include newly added configuration values.
Pull request changing this in mbed-os:
https://github.com/ARMmbed/mbed-os/pull/8106
> Update platform and rtos config docs

- docs/porting/connectivity/MeshInterface.md
Need to change the test-config name following change in mbed OS PR https://github.com/ARMmbed/mbed-os/pull/7996
> Fixed test-config name

- docs/tools/CLI/cli-compile.md
- docs/tools/CLI/cli-create.md
- docs/tools/CLI/cli-test-debug.md
- docs/tools/mbed_targets.md
As we have had several people stumble over finding this documentation,
I'm linking to it from everywhere we mentoin `--source`, as the build 
rules are the primary affect of the aforemntioned switch. 
[x] Fix
[ ] Refactor
[ ] Target update
[ ] Functionality change
[ ] Breaking change
> Link to build rules documentation

- docs/api/drivers/Ticker.md
> minor changes to ticker doc

- docs/tutorials/optimize/memory/runtime_mem_trace.md
- docs/tutorials/optimize/memory/runtime_stats.md
Update memory statics struct with overhead_size info.
> Updating docs with new struct members

- docs/api/drivers/Devicekey.md
Minor changes and example moved to https://github.com/ARMmbed/mbed-os-examples-docs_only/tree/master/DeviceKey
> DeviceKey page update

- docs/api/drivers/QuadSPI.md
https://github.com/ARMmbed/mbed-os/pull/8388
https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/1
> Qspi Update

- docs.json
As we have had several people stumble over finding this document, I'm
moving it to where they expected to find it. Personally, I also found
it odd that the landing page for configuring tools was some bootloader
configuration refenece.
[x] Fix
[ ] Refactor
[ ] Target update
[ ] Functionality change
[ ] Breaking change
> Move bootloader configuration from tools to reference

- docs/api/api.md
Fixed the link to the CAN apis.  It was pointing to a page on debugging instead of the correct API.
> Fix the link for the CAN api

- docs/api/rtos/Kernel.md
Kernel documentation updated with new additions to Kernel namespace:
A new example has been created as well: https://github.com/ARMmbed/mbed-os-example-kernel-hooks
> Kernel documentation updated with new additions to Kernel namespace

- docs/api/rtos/EventFlags.md
This is related to https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/6 and should wait for it, for the link to work.
> Move the EventFlags example to an external repo

- docs/porting/target/bootstrap.md
Update the linker script templates to include the ability to adjust the boot stack stack size.
This depends on the code change here:
https://github.com/ARMmbed/mbed-os/pull/8039
> Update linker script templates to include stack

- docs/tutorials/debug/debug_fault_exception.md
Update fault dump documentation with new crash-dump format
> Fault handler doc update

- docs/reference/contributing/guidelines/design_guidelines.md
- docs/reference/contributing/guidelines/style.md
- docs/reference/contributing/guidelines/workflow.md
We use inbound-outbound license. This follows the latest update to the
documentation that removed CLA page.
My latest update missed these, I realized after reviewing public docs that these are still there
cc @ARMmbed/mbed-os-maintainers
> workflow: remove explicit CLA references

- docs/porting/connectivity/NetworkStack.md
Socket porting part was missing information about non-blocking
behaviour of the underlying stack calls.
Connect call was not mentioning the default interfaces at all.
Testing section was having outdated information. Replaced with the
link to current test plan.
Modify the ESP case study with up to date JSON and test result.
> Clarify NetworkStack porting guide

- docs/tutorials/using_apis/connectivity/cellular_tcp.md
example is moved in https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/7
> Move code example to the examples repo

- docs/tools/CLI/cli-setup.md/cli-reqs.md
Docs PR for the following change: https://github.com/ARMmbed/mbed-cli/commit/629d2a8088f30f5b69d5bb75d254ad530d3d0e4d#diff-04c6e90faac2675aa89e2176d2eec7d8
(This particular commit I accidentally committed directly into mbed-cli)
The switch is because `pip` handles dependencies much better than `setup.py`.
When the change was made, it was found that using `setup.py` was pulling versions of packages that weren't even released (aka pyOCD beta packages).
> Updated mbed-cli install instructions to use 'pip' instead of 'setup.py'

- docs/tools/CLI/cli-compile.md
The code that implements this has been in master for a yearish
> Document the `--stats-depth` command line argument

- docs/tutorials/tutorials_intro.md
Move content about using the APIs to the tutorials overview page.
> Move using APIs content to tutorials_intro.md

- docs/reference/contributing/guidelines/workflow.md
Correct pull request states labels (eg. needs: review) in "Reviews" section and "The CI (Continuous Integration) testing" section.
> Fix pull request state labels in workflow.md

- docs/api/networksocket/TCPSocket.md
- docs/api/networksocket/UDPSocket.md
Documentation update according to this code change: https://github.com/ARMmbed/mbed-os/pull/8794
> Socket constructors which call open are deprecated

- docs/api/platform/Error.md
- docs/reference/runtime/Memory.md
Documentation for crash reporting feature in Mbed OS. This is targeted for 5.11 release.
> Crash reporting documentation

- docs/porting/storage/BlockDevice.md
Add command about porting tests.
> Add test command to BlockDevice.md

- docs/api/platform/MbedStats.md
https://github.com/ARMmbed/mbed-os/pull/8761 was merged, good to go!
Replace enabling stats API with macros to using the official config system.
@deepikabhavnani will this be accurate? It sounded like there was some potential changes in the required PR linked above.
> Move stats API docs to config format

- docs/tutorials/quickstart/cli_code.md
- docs/tutorials/quickstart/quick-start-cli-debug.md
- docs/tutorials/quickstart/quick-start-compiler.md
- docs/tutorials/quickstart/quick-start-online-debug.md
New quick start is replacing old blinky URL, revert to original name. 
Pending:
~https://github.com/ARMmbed/mbed-os-example-blinky/pull/144~
Merged! Good to go.
> Revert quick-start-blinky references

- docs/reference/contributing/guidelines/guidelines.md
Each repo should contain license & contributing information
I added it  to the guidelines (new section - new repository). This should be valid for any repository we release. 3 files that are important for contribution.
@ARMmbed/mbed-os-maintainers Please review
> guidelines: add repository

- docs/reference/configuration/Storage.md
Added clarification for overriding pins for the SD component with the new configuration system
> Added SD component config clarification

- docs/porting/psa/spm.md
The document is currently Work In Progress but its structure and most of its contents is here.
It is loaded as a PR so it can be reviewed by tech-writers.
Current gaps:
- Doxygen should be generated once SPM HAL is finalized, and then corresponding links will be added.
- HAL tests names will be updated once finalized.
- New sections might be added.
> Add PSA-SPM porting guide

- docs/tutorials/debug/debug_with_printf.md
For some reason the `{:target="_blank"}` markdown hints are getting
rendered literally on the page:
https://os.mbed.com/docs/v5.8/tutorials/debugging-using-printf-statements.html#video-tutorials
Perhaps this is a doc engine bug?  Remove them for now so they don't
show up on the page.
> Remove target=blank from the youtube links

- docs/api/platform/MpuManagement.md
- docs/reference/configuration/Platform.md
Add information to the MPU management page about using the config "platform.disable-mpu" to disable the MPU to save space. Also update the platform configs to include this new value.
This PR has a code dependency on:
https://github.com/ARMmbed/mbed-os/pull/9040
> Document how to turn MPU off at compile time

- docs/porting/porting_full_process/built_in_tests.md
- docs/porting/porting_full_process/demo_testing.md
- docs/porting/porting_full_process/porting.md
- docs/porting/porting_full_process/porting_reqs.md
- docs/porting/porting_full_process/porting_start.md
I've included quite a bit of comments and corrections here. **This PR isn't intended to be merged as is,** its more like a starting point of feedback that can be referenced.
I only covered the "Porting process" section in the porting guide. The guide is quite extensive and has lots of potential!
> Feedback on porting guide

- docs.json
- docs/reference/api/drivers/Serial.md
- docs/reference/contributing/storage/BlockDevice.md
- point to latest release process docs
- remove example, with no corresponding repo
- use 5.6 release header file
> Fix 5.6 errors

- docs/api/storage/KVStoreGlobalAPI.md
After a security review. Doxygen needs to be generated after https://github.com/ARMmbed/mbed-os/pull/8987 is merged
> remove KV_REQUIRE_INTEGRITY_FLAG

- docs/reference/configuration/configuration.md
Additionally add small blurb on how not setting the value field/setting it to null affects the parameter (this might've been described somewhere else, let me know if this is already here and we can remove that portion).
> Add config options range limit notes

- docs/reference/contributing/guidelines/workflow.md
Authors can request specific reviewers in addition to those automatically
assigned by the CI bot. The review section of the workflow has been
updated to document this.
> Add a comment about requesting specific reviewers
