- docs/dev_tools/third_party.md
@theotherjimmy I've put your edits and mine on top of the old file for 5.2
> Edit on Jimmy's edits

- docs/advanced/runtime_stats.md
- docs/concepts/memory_model.md
Update memory map and add documentation on metrics.
> Stack and heap updates

- docs/cont/design_guidelines.md
Add design guidelines, this is not a part of code-style or contribution guidelines.
cc: @iriark01, @sg- 
previously hosted here: https://github.com/ARMmbed/mbed-os-morpheus/blob/guidelines/GUIDELINES.md
> Add design guidelines

- docs/dev_tools/adding_exporters.md
Not sure if this goes here. Feel free to move this.
@iriark01
> Add a page about adding new exporters

- docs/getting_started/blinky_cli.md
I changed "you" to "your" under "Getting Blinky".
> Changed "you" to "your"

- docs/advanced/mbed_targets.md
Changed "tools/target.json" to "targets/targets.json"
> Minor: Fix targets.json path

- docs/advanced/testing.md
Fixed "mbedignore" link break in testing.md
> Minor: Fix "mbedignore" link break

- docs/dev_tools/third_party.md
https://github.com/ARMmbed/mbed-os/issues/3338#issuecomment-263917168
This new blurb should prevent issues like the one linked above.
> Add compilers to path for make

- docs/advanced/tls_hardware_acceleration.md
Adds documentation for the TLS hardware acceleration support.
> Mbedtls hardware acceleration

- docs/advanced/runtime_stats.md
> Fix links in runtime_stats.md

- docs/advanced/tls_porting.md
> Fix minor miswording in tls_porting.md

- docs/advanced/intro.md
Update transclusion link from 5.1 to 5.3 because content has changed
> Update link in intro.md

- docs/concepts/memap.md
> Fix broken internal links on memap.md

- docs/getting_started/examples.md
@iriark01 
The first one is technically not an example, but probably good to link to anyway.
> Add JS on mbed links

- mkdocs.yml
Make exporters page visible and maybe fix issue #95 (https://github.com/ARMmbed/Handbook/issues/95)
> Add exporters to YML

- docs/cont/adding_exporters.md
I've added some additional/missing information for the 'adding a new exporter' documentation.
@theotherjimmy please review!
> Additional documentation for adding a new exporter

- docs/advanced/exporters.md
> Update link in exporters.md

- docs/advanced/exporters.md
- docs/debugging/Keil.md
- docs/debugging/compile_time.md
- docs/debugging/debug_builds.md
- docs/debugging/debugging.md
- docs/debugging/debugging_eclipse_pyocd.md
- docs/debugging/debugging_microbit.md
- docs/debugging/lights_of_dead.md
- docs/debugging/other_ides.md
- docs/debugging/printf.md
- docs/debugging/toolchain.md
- docs/debugging/vscode.md
Move debugging docs from stand-alone project to master by copying existing pages and pasting them here before changing YML
> Move debuggging docs

- docs/advanced/exporters.md
- docs/dev_tools/third_party.md
Add a section in the third_party.md, plus a short explanation in exports.md.
> Add GNU ARM Eclipse exporter

- docs/debugging/vscode.md
> Apply https://github.com/ARMmbed/Debugging-docs/pull/10 to this repo

- docs/advanced/bootloader.md
- docs/advanced/flash.md
Please review
The bootloader should link to flash porting guide thus I added a reference here.
cc @c1728p9 @ashok-rao
> Bootloader - add new references

- docs/advanced/mbed_targets.md
Now with more key definitions!
> Edit and update targets.json docs

- docs/advanced/porting_guide.md
May or may not have come out ahead
Might resolve #138
> Wrestled with the porting guide

- docs/advanced/porting_guide.md
- docs/cont/code_style.md
> Add section on compiler flags

- docs/advanced/bootloader.md
Reverts ARMmbed/Handbook#149 because the content is not merged yet
> Revert "Add unmanaged bootloader documentation"

- docs/debugging/vscode.md
See also https://github.com/ARMmbed/mbed-os/pull/3915
@anotherbutler
Maybe the wording is a bit much...
> vscode: Note about the path to arm-none-eabi-gdb

- docs/dev_tools/third_party.md
> Add note about possible bad flags in makefile exports

- docs.json
Fix typo in API references section
> Fix typo in docs.json

- docs/compile/build_profiles.md
Apply changes from merged PR #140
> Apply new 5.5 changes to build_profiles.md

- docs/advanced/tls_hardware_acceleration.md
Added considerations on power management and concurrency.
Supersedes PR #168
> Add warnings to TLS hardware acceleration guide about concurrency and power management

- docs/advanced/mbed_targets.md
It's a file in the root of a project directory where you can define
custom targets.
Documentation for ARMmbed/mbed-os#4103
> Add `custom_targets.json` description

- docs/dev_tools/third_party.md
Update version numbers to match PR #182
> Update version numbers in third_party.md

- mkdocs.yml
WAIT UNTIL PR #187 MERGES BEFORE MERGING
> Add CLI installer page to YML

- docs/advanced/config_system.md
@rene-aguirre Could you review?
Resolves https://github.com/ARMmbed/mbed-os/issues/4723
> Hightlight move of custom targets

- docs/refs/api/networking/cellular.md
Rephrase imprecise "abstraction layer" text with more precise language.
> Rephrase text in cellular.md

- docs/tutorials/optimize/memory/memory_intro.md
Content derived from https://developer.mbed.org/blog/entry/Optimizing-memory-usage-in-mbed-OS-52/
> Created memory_intro article

- docs/refs/api/drivers/InterruptIn.md
added context to explanation and pointer to event que doc for how to do printf's form interrupt context
> add context

- docs/refs/api/security/tls.md
- docs/refs/api/security/uvisor.md
Reorganizes and clarifies information in the Security section of the docs
> Reorganize security section

- docs/refs/api/connectivity/conn_intro.md
- docs/refs/api/connectivity/mesh.md
Moved bulk of mesh section to top level. Simplified api page to look like other api docs. Need to move examples to hosted repos in dev site
@sg- There are a few examples that are inlined right now and I think these should be hosted somewhere as stand alone examples. Where would you like me to put them so you guys can have control over them?
> update mesh section

- docs/refs/api/drivers/AnalogOut.md
Add details about 0.0 -> 1.0 range of the API.
> Add explanation of range

- docs/refs/api/connectivity/conn_intro.md
- docs/refs/api/connectivity/mesh.md
* Add links to mesh APIs
* Add link to generic example rather than inline code snippets.
> Condense mesh section and add mesh API references

- docs/refs/api/drivers/BusOut.md
add corner case notes to the tips section
> Expand on description in BusOut

- docs/refs/api/drivers/BusIn.md
expand explanation, add corner cases as tips / things to watch out for based on my experience
> Expand explanation on BusIn

- docs/refs/api/drivers/BusInOut.md
expanded description and added corner case information
> Added more detail to BusInOut

- docs/refs/api/connectivity/conn_intro.md
Fix subheadings of the connectivity intro to make them nest properly.
> Fix connectivity intro

- docs/refs/api/drivers/AnalogIn.md
- docs/refs/api/drivers/AnalogOut.md
- docs/refs/api/drivers/CAN.md
- docs/refs/api/drivers/DigitalInOut.md
- docs/refs/api/drivers/I2C.md
- docs/refs/api/drivers/I2CSlave.md
- docs/refs/api/drivers/InterruptIn.md
- docs/refs/api/drivers/PortIn.md
- docs/refs/api/drivers/PortInOut.md
- docs/refs/api/drivers/PortOut.md
- docs/refs/api/drivers/PwmOut.md
- docs/refs/api/drivers/SPI.md
- docs/refs/api/drivers/SPISlave.md
- docs/refs/api/drivers/Serial.md
- docs/refs/api/drivers/Ticker.md
- docs/refs/api/drivers/TimeOut.md
- docs/refs/api/drivers/Timer.md
- docs/refs/api/drivers/flashiap.md
- Reviewed Drivers API section
- Moved warnings/notes/tips above the API links and code examples
- Removed links to Wikipedia
> Reviewed Drivers API section

- docs/intros/terms.md
- Added terms
- Added definitions
- Updated capitalization for terms
> Adding terms & definition to glossary

- docs/refs/api/rtos/events.md
it was pointing at a source file, now pointing at correct reference.
> event library update

- docs/refs/api/storage/storage_intro.md
> Split list of required filesystem apis

- docs/tools/offline/cli.md
And add a section about the priority between multiple toolcahin
configurations
> Rewrite toolchain configuration in preference order

- docs/tools/offline/cli.md
Make changes from PR #251 to avoid merge conflicts.
> Make changes from PR #251

- docs/reference/contributing/target/rtos.md
Updating document based on RTX code changes in ARMmbed/mbed-os#5105 ARMmbed/mbed-os#4875 ARMmbed/mbed-os#5003 ARMmbed/mbed-os#4991
@bulislaw @0xc0170 @AnotherButler - Please review
> Rtos changes

- docs/reference/api/platform/Callback.md
The implementation class actually has member functions.
cc @AnotherButler
> Point callback reference to implementation class

- docs/reference/api/platform/Callback.md
Address https://github.com/ARMmbed/Handbook/issues/282
Is this a better phrasing or would you like something tweaked?
@AnotherButler
> Rephrase link to introduction to callbacks

- docs/tools/mbed_targets.md
@theotherjimmy 
@AnotherButler
> Clarify using mbed CLI vs compiler for custom targets

- docs/reference/api/storage/MBRBlockDevice.md
@sg-
The first example also uses HeapBlockDevice, should I cross reference this doc with HeapBlockDevice?
> Add MBRBlockDevice API reference doc

- docs/reference/api/storage/HeapBlockDevice.md
> Add HeapBlockDevice API docs

- docs/reference/runtime/Execution.md
> Extend runtime exectution page

- docs/reference/api/platform/CircularBuffer.md
Added usage of CircularBuffer API in mbed-os repo instead of example.
https://jira.arm.com/browse/IOTMORF-1281
@AnotherButler @sg- Please review.
> Updated CircularBuffer doc

- docs/reference/api/connectivity/networksocket/SocketAddress.md
Added an example to fetch ip address and port using socket address.
@sg- Please review
> SocketAdress Class doc update

- docs/reference/runtime/Memory.md
> Runtime memory page update

- docs/reference/api/connectivity/networksocket/TCPServer.md
Jira: https://jira.arm.com/browse/IOTMORF-1311
Added the example reference of TCP server
@AnotherButler  @sg- Please review
> Updated TCP Sever doc

- docs/reference/api/platform/CallChain.md
> Revert "Remove CallChain since it isn't public API"

- docs/reference/api/connectivity/networksocket/TCPSocket.md
Jira: https://jira.arm.com/browse/IOTMORF-1310
Added the example reference of Wifi and Ethernet HTTP client.
> TCP sockect doc update

- docs/reference/api/storage/SlicingBlockDevice.md
> Add API docs for SlicingBlockDevice

- docs/reference/runtime/Bootstrap.md
New runtime bootstrap page documenting user hooks and retargeting.
@AnotherButler @sg-
> Create runtime bootstrap page

- docs/reference/api/platform/NonCopyable.md
Added usage of NonCopyable API in mbed-os repo instead of example.
https://jira.arm.com/browse/IOTMORF-1293
@AnotherButler @sg- Please review.
> Updated NonCopyable doc

- docs/reference/contributing/target/bootstrap.md
Update the bootstrap page by adding information on linker script changes and adding newer information about the files cmsis.h, cmsis_nvic.h, mbed_rtx.h and targets.json.
> Update bootstrap.md to contain more information

- docs/reference/api/connectivity/bluetooth/iBeacon.md
This page describes what the iBeacon technology is and what the iBeacon class do.
> BLE: Add iBeacon reference.

- docs/reference/contributing/target/bootstrap.md
Some changes to bootstrap contributing page.
@sg-
> Changes to bootstrap contributing page

- docs/tools/offline/cli-setup.md
Update mbed CLI used by installer to version 1.2.2
> Update Mbed CLI Windows Installer link to version 0.4.3

- docs/reference/api/connectivity/bluetooth/HeartRateService.md
This page describes what the Bluetooth Heart Rate Service is and what the HeartService class do.
> BLE: Add reference of Heart rate service.

- docs/reference/api/connectivity/networksocket/networksocket.md
@AnotherButler Two new examples, as discussed
> Add UDP and TCP ping-pong examples.

- docs/tools/mbed_targets.md
@AnotherButler - This PR is valid for 5.6 + 5.7
> Add v8 architecture support in tools

- docs/reference/contributing/guidelines/workflow.md
Resolve IOTMORF-1776 by adding material about required documentation and testing, and clarify patches from pull requests.
> Update workflow.md to make requested changes

- docs/reference/api/drivers/LowPowerTicker.md
- docs/reference/api/drivers/Ticker.md
Fill in LowPowerTicker.md with content and make a slight update to Ticker.
> Write docs page for LowPowerTicker

- docs/reference/api/platform/Time.md
> Indicates that 'time' function cannot be used in isr

- docs/tutorials/using_apis/mesh/thread_commissioning.md
- Specified where add commissioning flags in .json file
- Added allowd characters for PSKd
> Doc update for Thread commissioning

- docs/reference/api/rtos/Mutex.md
Add requested link to PlatformMutex API.
> Link Mutex.md to PlatformMutex

- docs/tutorials/debug/eclipse_pyocd.md
Fix issue #331 by updating text and link.
> Update eclipse_pyocd.md to fix issue #331

- docs/reference/configuration/Connectivity.md
Generated via:
`mbed compile --config -m K64F -t GCC_ARM -v`
@AnotherButler
> Update connectivity config options

- docs/reference/api/drivers/Serial.md
> Serial: fix serial 3 example - use rev2

- docs/tutorials/using_apis/events_tutorial.md
> events: latest event example fixes IRQ printf issue

- docs.json
Add level to contributing for ease of use and consistent rendering.
> Update contributing structure in docs.json

- docs.json
Reverts ARMmbed/Handbook#385 because the engine gave me a 500 error.
> Revert "Update contributing structure in docs.json"

- docs/tools/offline/cli-create.md
@AnotherButler
Resolves https://github.com/ARMmbed/mbed-cli/issues/437
> Minor edits to `mbed compile` arguments section

- docs/reference/contributing/guidelines/style.md
@pan- This should fix #292 (we might want to add more, let me know). Your issue had it nicely described ,thanks for all that info there.
Reason: the current codebase (most of it) follows what is described here
> Add pointer and references examples

- docs/reference/contributing/target/rtc.md
> Update RTC contributing page to agreed template

- docs.json
- docs/reference/contributing/target/lp_ticker.md
- docs/reference/contributing/target/ticker.md
- docs/reference/contributing/target/us_ticker.md
Add the contributing pages for the microsecond ticker and the low power ticker.
> Add Ticker contributing pages

- docs/tools/mbed_targets.md
> Spelling Fixes

- docs/tools/offline/mbed-studio.md
Added a pre-requisites section.
> Prerequisites

- docs/tutorials/debug/debug_fault_exception.md
Update the crash dump documentation with new info added to crash dump.
> Update crash dump docs with additional info

- docs/tutorials/mbed-os-2-vs-5.md
Fixed an image link in the mbed-os-2-vs-5 file
> Fixed image link

- docs/tutorials/debug/debug_fault_exception.md
Add more description around imprecise bus faults and added more clarifications.
> Add more description around imprecise bus faults

- docs/tools/toolchains/export_to_third_party.md
Resolves armmbed/mbed-os-example-sockets#68
@AnotherButler could you edit?
> Describe the error when make does not have a compiler

- docs/reference/api/drivers/MbedCRC.md
MbedCRC class page added for 5.8
@AnotherButler
> MbedCRC page added

- docs/reference/contributing/guidelines/workflow.md
Already in mbed OS: https://github.com/ARMmbed/mbed-os/pull/6348
> workflow: fix PR type template

- docs/tools/offline/cli-setup.md
> Add note about multiple compilers

- docs/tutorials/quickstart/quick-start-cli.md
Update link from private repo to link from tools section.
> Update link in quick-start-cli.md

- docs/reference/api/connectivity/networksocket/EthInterface.md
> TCPSocket_ConnStateCb_Example Mbed OS lib updated to 5.8

- docs/reference/contributing/target/ResetReason.md
- docs/reference/contributing/target/Watchdog.md
Added draft of the contributing pages for Watchdog and Reset Reason HAL APIs
> Contributing Page: Watchdog and Reset Reason

- docs/reference/contributing/guidelines/guidelines.md
Small introduction to guidelines
> Add context to Guidelines

- docs/reference/api/platform/Wait.md
Change warning as requested by engineering in mbed-os PR #6645
> Change warning

- docs/reference/api/platform/MbedStats.md
Examples were updated to support Mbed OS 5, as a result links to main file changed.
> Corrected links to example main files

- docs/tools/tools_intro.md
Change Arm compiler version to that of 5.9.
> Update Arm compiler version

- docs/reference/api/connectivity/networksocket/DNS.md
Interface will be merged to mbed-os master in:
https://github.com/ARMmbed/mbed-os/pull/6847
Header for DNS interface is here (on to be merged branch):
https://github.com/ARMmbed/mbed-os/blob/feature-emac/features/netsocket/DNS.h
> Asynchronous DNS interface

- docs/reference/api/drivers/Devicekey.md
> DeviceKey ROT user API

- docs/reference/api/storage/BlockDevice.md
Fix image for block device erase block
cc @AnotherButler @kegilbert
> Fix image for block device erase block

- docs/reference/contributing/guidelines/workflow.md
Two main changes:
- every change in pull request should result in a comment (PR rebased, added new test, more devices support added, rewrote the history, etc) - helps keep tracking and the intention of the update
- another one is about rereview - if a change was approved by a technical person, and no change from technical point of view, then maintainers approval should be sufficient. For instance, documentation update, rebase on top of master, rewriting history, style changes and similar.
@ARMmbed/mbed-os-maintainers @bulislaw Please review
> Workflow: add details for review

- docs/reference/contributing/target/itm.md
> Minor tweaks on ITM docs regarding branding

- docs/reference/api/drivers/Devicekey.md
According to https://jira.arm.com/browse/IOTDOCS-506
> Devicekey updates

- docs/reference/api/storage/FileSystem.md
These numbers were verified by Haster
> Sector requirements IOTDOCS-508

- docs/reference/api/platform/Error.md
Added more code snippets to demonstrate usage of Error handling APIs and fix a minor issue with error history docs.
> Add more examples and error history fixes

- docs/introduction/terms.md
Requested from:
https://github.com/ARMmbed/Handbook/pull/561#discussion_r193129782
@AnotherButler
> Add RAII to glossary

- docs/reference/api/storage/NVStore.md
Add requested content from the NVStore example to the Handbook.
> Add NVStore example content to Handbook

- docs/reference/api/drivers/LowPowerTimeout.md
- docs/reference/api/drivers/LowPowerTimer.md
https://jira.arm.com/browse/IOTMORF-1302
https://jira.arm.com/browse/IOTMORF-1303
CC @AnotherButler @sg- @c1728p9
> Low power timer / timeout docs updated

- docs/reference/technology/connectivity/cellular.md
Add images, standardize hosted module naming and delete misleading statement, as requested by OOB in issue #550.
> Add requested changes to cellular.md

- docs/tutorials/quickstart/quick-start-cli.md
Fix typo to resolve IOTDOCS-512.
> Fix typo in quick-start-cli.md

- docs/reference/api/platform/Error.md
Fixes and updates to capture OOB reported issues:
https://github.com/ARMmbed/Handbook/issues/580
https://github.com/ARMmbed/Handbook/issues/582
> Update error handling docs with OOB feedbacks

- docs/reference/technology/connectivity/ethernet.md
Make changes caught in review to resolve issue: https://github.com/ARMmbed/mbed-os-example-sockets/issues/81
> Resolve issue raised in mbed-os-example-sockets

- docs/reference/api/platform/MemTrace.md
- docs/tutorials/optimize/memory/runtime_mem_trace.md
https://jira.arm.com/browse/IOTMORF-1283
@AnotherButler - Shall we add reference of tutorial doc which has more details?
https://os.mbed.com/docs/v5.7/tutorials/optimizing.html#runtime-memory-tracing
> Added memory trace doc

- docs/reference/configuration/configuration.md
> Add `artifact_name` section to mbed_app example

- docs/reference/api/drivers/MbedCRC.md
Update link to point to latest source in example
> Update revision of example

- docs/tools/offline/mbedignore.md
Resolves https://github.com/ARMmbed/mbed-cli/issues/378
> Correct mbed CLI usage and Edit

- docs/reference/api/platform/Error.md
Updates to Error docs to capture the new config names and added example
> Updates to Error docs to capture the new config names and added example

- docs/reference/api/drivers/AnalogIn.md
Included information about the successive-approximation ADC type and resolution in AnalogIn.md
> Updates to AnalogIn.md

- docs/APIs/intro.md
- docs/advanced/DAP.md
- docs/advanced/config_system.md
- docs/advanced/debugging.md
- docs/advanced/intro.md
- docs/advanced/testing.md
- docs/advanced/tls_porting.md
- docs/collab/collab_intro.md
- docs/collab/mult_auth.md
- docs/collab/publishing_code.md
- docs/collab/pull_requests.md
- docs/collab/versions.md
- docs/concepts/events.md
- docs/concepts/memory_model.md
- docs/cont/code_style.md
- docs/cont/contributing.md
- docs/dev_tools/cli.md
- docs/dev_tools/online_comp.md
- docs/dev_tools/options.md
- docs/dev_tools/studio.md
- docs/dev_tools/third_party.md
- docs/getting_started/blinky_cli.md
- docs/getting_started/blinky_compiler.md
- docs/getting_started/examples.md
- docs/getting_started/first_program.md
- docs/getting_started/mbed_interface.md
- docs/getting_started/serial_communication.md
- docs/getting_started/what_need.md
- docs/getting_started/where_next.md
- docs/index.md
> Updated version redirects from 5.1 to latest

- docs/reference/api/connectivity/bluetooth/bluetooth.md
WORK IN PROGRESS
Add initial information.
> Add BLE content

- docs/reference/api/usb/USBAudio.md
- docs/reference/api/usb/USBCDC.md
- docs/reference/api/usb/USBHID.md
- docs/reference/api/usb/USBKeyboard.md
- docs/reference/api/usb/USBMIDI.md
- docs/reference/api/usb/USBMSD.md
- docs/reference/api/usb/USBMouse.md
- docs/reference/api/usb/USBMouseKeyboard.md
- docs/reference/api/usb/USBSerial.md
- docs/reference/api/usb/usb_component.md
Add the API reference for the various USB classes.
Most of the content was moved into this PR from:
https://os.mbed.com/handbook/USBDevice
> Add USB class documentation

- docs/tools/mbed_targets.md
GCC_ARM has issues, only ARMC6 supported
CC @SenRamakri
> Update toolchain support for ARMv8M

- docs/reference/contributing/target/entropy.md
Not sure why these did not go through in the 1st pull request.
> TLS-correction 3

- docs/tools/offline/cli-setup.md
added references to installers to encourage the default behavior, USE AN INSTALLER.
> Updating Installer Instructions

- docs/reference/api/drivers/SPI.md
Update SPI docs with multiple slave scenario and usage
> Update SPI docs with multiple slave scenario

- docs/reference/contributing/contributing.md
Actually list all of the sections
> Revise contributing overview

- docs.json
- docs/tools/build_rules.md
> Document Source Discovery rules

- docs/reference/contributing/guidelines/design_guidelines.md
Update to capture new design process and template
> Update to capture new design process and template

- docs/reference/api/security/TLS.md
Update the forum link to the new Mbed corum for Mbed TLS.
> Update the Mbed TLS forum link

- docs/reference/api/storage/storage.md
Fix branding to resolve issue 65 (https://github.com/ARMmbed/mbed-os-example-filesystem/issues/65)
> Fix branding in storage.md

- docs/reference/contributing/target/bootloader.md
Fix link to resolve issue #709
> Fix link in bootloader.md

- docs/tools/build_rules.md
Fix broken link to resolve issue #722
> Fix link in build_rules.md

- docs/tools/mbed_targets.md
> Fix line number in mbed_targets.md

- docs/tools/mbed_targets.md
Add missing parenthesis to resolve issue #717
> Fix punctuation in mbed_targets.md

- docs/tools/mbed_targets.md
Fix broken link to resolve issue #716
> Fix broken link in mbed_targets.md

- docs/tools/offline/cli-device-management.md
Change code snippet to use generic commands, and fix phrasing to resolve issue #711
> Change code snippet in cli-device-management.md

- docs/reference/api/platform/MemTrace.md
Overhead is added only in case of memory stats and not memory trace
> Corrected overhead

- docs/tools/testing/unit_testing.md
Add link to instructions to be coherent with greentea and icetea docs and to resolve issue #718
> Add link to unit_testing.md

- docs/tools/toolchains/export_to_third_party.md
Show how to get list of supported export targets.
@ConradBraam
> Add note export command help

- docs/tools/offline/cli-test-debug.md
- docs/tools/testing/testing_icetea.md
Fixing a few missing punctuation/markup as well as making minor grammar tweaks.
> Fixing a few issues with icetea documentation

- docs/tools/offline/cli-device-management.md
Add need for PDMC and bootloader, as requested in issue #707
> Add need for PDMC in cli-device-management.md

- docs/reference/contributing/guidelines/workflow.md
Add content about two-factor authentication requirement
> Add 2FA content to workflow.md

- docs/tools/testing/testing_intro.md
- docs/tools/testing/unit_testing.md
Adds:
- instructions how to install the prerequisites
- detailed instructions how to use the tool
> Improve unit testing documentation

- docs/tools/mbed_targets.md
Adding documentation for is_disk_virtual and detect_code field
> Documentation for target fields

- docs/api/platform/PowerManagement.md
Move idle loop content to its own page.
> Move idle loop from PowerManagement.md

- docs/reference/contributing/guidelines/workflow.md
@NirSonnenschein To complete the update, need your username on mbed.com please
> workflow: update maintainers

- docs/api/drivers/SPI.md
Add context to example for clarity.
> Add intro to example in SPI.md

- docs/api/platform/Error.md
Error.md updated with latest info and fixed errors
> Fix spelling errors and update info

- docs/tools/testing/utest.md
taken out deprecated minar tests
> working snippet for utest

- docs/api/usb/USBMIDI.md
- add Play "Take Me Out to the Ball Game" example
> Changes to USBMIDI.md

- docs/api/usb/USBHID.md
- docs/reference/api/usb/USBHID.py
- modify USBHID example by adding a helper Python script
> Changes to USBHID.md

- docs/tutorials/using_apis/flow_control.md
> Update Flow Control tutorial code links

- docs/reference/runtime/Execution.md
This updates the example to makes use of the Idle thread as well showing the different execution modes (Thread and Handler).
> Updating execution example

- docs/porting/target/sleep.md
- docs/tools/mbed_targets.md
Update the docs to explain to STCLK_OFF_DURING_SLEEP.
> Add docs on STCLK_OFF_DURING_SLEEP

- docs/api/platform/ATCmdParser.md
Example update and links corrected 
https://github.com/ARMmbed/mbed-os-example-atcmdparser/pull/1
> Update doc and example

- docs/tools/tools_intro.md
Add ARMC6 version in the Online Compiler.
> Add compiler version

- readme.md
Pretty sure we're on 5.10 now :)
> Update readme.md to mention our latest version is 5.10

- docs/api/platform/PlatformMutex.md
Docs update for the `PlatformMutex` class.
> PlatformMutex docs update

- docs/api/nfc/NDEF.md
Move APIs into own pages, and keep this page as overview to match other sections.
> Move content from NDEF.md

- docs/tutorials/using_apis/how_to_api.md
Move from comma separate list of tutorials to categories. Will be expanding this list with the new tutorials. Open to suggestions on whitespace/component layout. Moved connectivity up as we get requests to highlight the networking components of Mbed OS more as an IoT platform.
@AnotherButler
> Reorganize Using APIs page

- docs/api/drivers/drivers.md
Add content about the blocking nature of APIs.
WIP: DO NOT MERGE
> Add content to drivers.md

- docs/tutorials/quickstart/quick-start-example-readme.md
> Reduce header size of debug troubleshooting section

- docs/reference/contributing/guidelines/license.md
@ARMmbed/mbed-os-maintainers 
I'll wait OK from the licensing team that proposed this addition
> license: define what acceptence we have for licenses in PR

- docs/api/platform/MbedStats.md
Dependent on https://github.com/ARMmbed/mbed-os/pull/8607
5.11 feature
> Add RAM/ROM info

- docs/tools/fastmodels/fastmodels.md
Adding documentation for Fast Models Ethernet function and `mbed-os-example-socket`
> update with Fast Models Ethernet functions

- docs/api/networksocket/SocketStats.md
Mbed OS 5.11 feature.
Dependent on https://github.com/ARMmbed/mbed-os/pull/8592
Todo:
CC @AnotherButler  @kegilbert @SenRamakri
> Add socket stats API documentation

- docs/porting/porting_full_process/built_in_tests.md
- docs/porting/porting_full_process/porting.md
- docs/porting/porting_full_process/porting_start.md
Below are my few comments/suggested changes for porting process.
> Suggested changes for porting guide

- docs/reference/contributing/guidelines/ci.md
this PR coresponds with ARMmbed/mbed-os#8889
> Update ci with PSA SPM travis job

- docs/tutorials/quickstart/example_walkthrough.md
Add new output in expected serial log in quick start guide
> Add RAM/ROM segment to output logs

- docs/porting/connectivity/CellularInterface.md
- docs/porting/connectivity/WifiInterface.md
- docs/porting/connectivity/ethernet.md
@iriark01 @MarceloSalazar Please review
> Add links to Network Socket test plan

- docs.json
- docs/api/api.md
- docs/api/platform/MpuManagement.md
- docs/api/platform/ScopedRamExecutionLock.md
- docs/api/platform/ScopedRomWriteLock.md
- docs/porting/target/mpu.md
- docs/porting/target/target.md
Add the HAL spec porting guide for the MPU API.
> Create the docs for the MPU API

- docs/reference/configuration/Storage.md
Link to storage components in Pelion Device Management site, as requested in issue #829
> Link to Pelion Device Management site

- docs/tools/CLI/cli-setup/cli-reqs.md
> Added table for toolchain environment variables

- docs/reference/api/drivers/Serial.md
> Fix 5.7 errors
